image: frekele/gradle:4.0-jdk8

stages:
#  - gradleTest
  - gradlePublish

#gradle-test:
#  stage: gradleTest
#  script:
#    - gradle test --refresh-dependencies

gradle-publish:
  stage: gradlePublish
  script:
    - gradle publish --refresh-dependencies
  only:
    - develop